Fixed: Passing of CLI args, Added: CLI args, Removed: Comments
protocollabs/maparo pull request #34
Opened 2019-01-21 09:19 UTC by monfron

- I didnt like the passing of cli args...the parameter list was getting too large
- new cli args for setting the update interval and measurement stop

Signed-off-by: monfron <simon.fronhoefer@gmail.com>

2019-01-22 18:54 UTC, hgn requested changes
schau dir mal die paar anmerkungen an, sonst super! Danke

2019-01-22 18:54 UTC, hgn commented on mapago-client.go
> +	msmtStopTime = flag.Uint("msmt-stop-interval", 10, "complete msmt time in seconds")
ohne msmt

```
--streams <n>
--listen-addr <addr> # das ist doch nicht die listen address?! -> --addr
--call-size ??? Nope! Wie bei iperf
--update-interval --> --ctrl-update-interval <n>
--stop-interval ? Kein Interval -> --measurement-time
```

2019-01-22 18:54 UTC, hgn commented on mapago-client.go
> +}
super! Richtig gut!

2019-01-23 13:24 UTC, monfron commented on mapago-client.go
> +	msmtStopTime = flag.Uint("msmt-stop-interval", 10, "complete msmt time in seconds")
ok fixed. listen-addr stand aber iwo noch im std

2019-01-23 13:26 UTC, monfron commented
New pull Request will be opened....

2019-01-23 13:26 UTC, closed without merging